-- V1: initial schema for the earthquakes table.
-- Column types mirror Hibernate 6.5 (Spring Boot 3.3) PostgreSQL defaults so that
-- `spring.jpa.hibernate.ddl-auto=validate` passes against JpaEarthquakeEntity.

CREATE TABLE earthquakes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    magnitude   FLOAT8                   NOT NULL,
    depth_km    FLOAT8                   NOT NULL,
    latitude    FLOAT8                   NOT NULL,
    longitude   FLOAT8                   NOT NULL,
    source      VARCHAR(255)             NOT NULL,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    risk_score  FLOAT8,                              -- nullable: set after scoring
    risk_level  VARCHAR(255),                        -- nullable: enum stored as string
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- Indexes match the @Index definitions on the entity.
CREATE INDEX idx_eq_occurred_at ON earthquakes (occurred_at);
CREATE INDEX idx_eq_lat_lon     ON earthquakes (latitude, longitude);
CREATE INDEX idx_eq_risk_level  ON earthquakes (risk_level);
